baseURL = "https://LiuHawke.github.io/"
languageCode = "zh-cn"
title = "LiuHawke Blog"
theme = "PaperMod"

[author]
  name = "LiuHawke"

[params]
  author = "LiuHawke"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true